# Generated by Django 4.0.5 on 2022-06-11 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=250, verbose_name='Наименование товара')),
                ('item_features', models.TextField(max_length=500, verbose_name='Характеристики')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(max_length=550, verbose_name='Описание')),
                ('is_in_stock', models.CharField(blank=True, choices=[('No', 'Нет в наличии')], max_length=100, null=True)),
                ('is_popular', models.BooleanField()),
                ('is_contract_price', models.BooleanField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
