# Generated by Django 4.0.5 on 2022-06-11 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_contract_price',
            field=models.BooleanField(default=False, verbose_name='Договорная цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_in_stock',
            field=models.CharField(blank=True, choices=[('No', 'Нет в наличии')], max_length=100, null=True, verbose_name='Есть ли в наличии?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный товар'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
