# Generated by Django 4.0.5 on 2022-06-11 09:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_amount_alter_item_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_features',
            field=ckeditor.fields.RichTextField(verbose_name='Характеристики'),
        ),
    ]
